//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLifeBooks.ChildProfile {
    
    
    public partial class Dashboard {
        
        /// <summary>
        /// SecurityTrimmedPanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DigitalLifeBooks.ServerControls.SecurityTrimmedPanel SecurityTrimmedPanel1;
        
        /// <summary>
        /// ImportantDocumentsRender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DigitalLifeBooks.UserControls.AlbumRender ImportantDocumentsRender;
        
        /// <summary>
        /// Albums control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater Albums;
    }
}
